package smpp

var commandIdByHex = map[string]map[string]string{
	"80000000": {"hex": "80000000", "name": "generic_nack"},
	"00000001": {"hex": "00000001", "name": "bind_receiver"},
	"80000001": {"hex": "80000001", "name": "bind_receiver_resp"},
	"00000002": {"hex": "00000002", "name": "bind_transmitter"},
	"80000002": {"hex": "80000002", "name": "bind_transmitter_resp"},
	"00000003": {"hex": "00000003", "name": "query_sm"},
	"80000003": {"hex": "80000003", "name": "query_sm_resp"},
	"00000004": {"hex": "00000004", "name": "submit_sm"},
	"80000004": {"hex": "80000004", "name": "submit_sm_resp"},
	"00000005": {"hex": "00000005", "name": "deliver_sm"},
	"80000005": {"hex": "80000005", "name": "deliver_sm_resp"},
	"00000006": {"hex": "00000006", "name": "unbind"},
	"80000006": {"hex": "80000006", "name": "unbind_resp"},
	"00000007": {"hex": "00000007", "name": "replace_sm"},
	"80000007": {"hex": "80000007", "name": "replace_sm_resp"},
	"00000008": {"hex": "00000008", "name": "cancel_sm"},
	"80000008": {"hex": "80000008", "name": "cancel_sm_resp"},
	"00000009": {"hex": "00000009", "name": "bind_transceiver"},
	"80000009": {"hex": "80000009", "name": "bind_transceiver_resp"},
	"0000000b": {"hex": "0000000b", "name": "outbind"},
	"00000015": {"hex": "00000015", "name": "enquire_link"},
	"80000015": {"hex": "80000015", "name": "enquire_link_resp"},
	"00000021": {"hex": "00000021", "name": "submit_multi"},
	"80000021": {"hex": "80000021", "name": "submit_multi_resp"},
	"00000102": {"hex": "00000102", "name": "alert_notification"},
	"00000103": {"hex": "00000103", "name": "data_sm"},
	"80000103": {"hex": "80000103", "name": "data_sm_resp"},

	// v4 codes

	"80010000": {"hex": "80010000", "name": "generic_nack_v4"},
	"00010001": {"hex": "00010001", "name": "bind_receiver_v4"},
	"80010001": {"hex": "80010001", "name": "bind_receiver_resp_v4"},
	"00010002": {"hex": "00010002", "name": "bind_transmitter_v4"},
	"80010002": {"hex": "80010002", "name": "bind_transmitter_resp_v4"},
	"00010003": {"hex": "00010003", "name": "query_sm_v4"},
	"80010003": {"hex": "80010003", "name": "query_sm_resp_v4"},
	"00010004": {"hex": "00010004", "name": "submit_sm_v4"},
	"80010004": {"hex": "80010004", "name": "submit_sm_resp_v4"},
	"00010005": {"hex": "00010005", "name": "deliver_sm_v4"},
	"80010005": {"hex": "80010005", "name": "deliver_sm_resp_v4"},
	"00010006": {"hex": "00010006", "name": "unbind_v4"},
	"80010006": {"hex": "80010006", "name": "unbind_resp_v4"},
	"00010007": {"hex": "00010007", "name": "replace_sm_v4"},
	"80010007": {"hex": "80010007", "name": "replace_sm_resp_v4"},
	"00010008": {"hex": "00010008", "name": "cancel_sm_v4"},
	"80010008": {"hex": "80010008", "name": "cancel_sm_resp_v4"},
	"00010009": {"hex": "00010009", "name": "delivery_receipt_v4"},
	"80010009": {"hex": "80010009", "name": "delivery_receipt_resp_v4"},
	"0001000a": {"hex": "0001000a", "name": "enquire_link_v4"},
	"8001000a": {"hex": "8001000a", "name": "enquire_link_resp_v4"},
	"0001000b": {"hex": "0001000b", "name": "outbind_v4"},
}

var commandStatusByHex = map[string]map[string]string{
	"00000000": {"hex": "00000000", "name": "ESME_ROK", "description": "No error"},
	"00000001": {"hex": "00000001", "name": "ESME_RINVMSGLEN", "description": "Message Length is invalid"},
	"00000002": {"hex": "00000002", "name": "ESME_RINVCMDLEN", "description": "Command Length is invalid"},
	"00000003": {"hex": "00000003", "name": "ESME_RINVCMDID", "description": "Invalid Command ID"},
	"00000004": {"hex": "00000004", "name": "ESME_RINVBNDSTS",
		"description": "Incorrect BIND Status for given command"},
	"00000005": {"hex": "00000005", "name": "ESME_RALYBND", "description": "ESME Already in bound state"},
	"00000006": {"hex": "00000006", "name": "ESME_RINVPRTFLG", "description": "Invalid priority flag"},
	"00000007": {"hex": "00000007", "name": "ESME_RINVREGDLVFLG", "description": "Invalid registered delivery flag"},
	"00000008": {"hex": "00000008", "name": "ESME_RSYSERR", "description": "System Error"},
	"0000000a": {"hex": "0000000a", "name": "ESME_RINVSRCADR", "description": "Invalid source address"},
	"0000000b": {"hex": "0000000b", "name": "ESME_RINVDSTADR", "description": "Invalid destination address"},
	"0000000c": {"hex": "0000000c", "name": "ESME_RINVMSGID", "description": "Message ID is invalid"},
	"0000000d": {"hex": "0000000d", "name": "ESME_RBINDFAIL", "description": "Bind failed"},
	"0000000e": {"hex": "0000000e", "name": "ESME_RINVPASWD", "description": "Invalid password"},
	"0000000f": {"hex": "0000000f", "name": "ESME_RINVSYSID", "description": "Invalid System ID"},
	"00000011": {"hex": "00000011", "name": "ESME_RCANCELFAIL", "description": "Cancel SM Failed"},
	"00000013": {"hex": "00000013", "name": "ESME_RREPLACEFAIL", "description": "Replace SM Failed"},
	"00000014": {"hex": "00000014", "name": "ESME_RMSGQFUL", "description": "Message queue full"},
	"00000015": {"hex": "00000015", "name": "ESME_RINVSERTYP", "description": "Invalid service type"},
	"00000033": {"hex": "00000033", "name": "ESME_RINVNUMDESTS", "description": "Invalid number of destinations"},
	"00000034": {"hex": "00000034", "name": "ESME_RINVDLNAME", "description": "Invalid distribution list name"},
	"00000040": {"hex": "00000040", "name": "ESME_RINVDESTFLAG",
		"description": "Destination flag is invalid (submit_multi)"},
	"00000042": {"hex": "00000042", "name": "ESME_RINVSUBREP",
		"description": "Invalid `submit with replace` request (i.e. submit_sm with replace_if_present_flag set)"},
	"00000043": {"hex": "00000043", "name": "ESME_RINVESMCLASS", "description": "Invalid esm_class field data"},
	"00000044": {"hex": "00000044", "name": "ESME_RCNTSUBDL", "description": "Cannot submit to distribution list"},
	"00000045": {"hex": "00000045", "name": "ESME_RSUBMITFAIL", "description": "submit_sm or submit_multi failed"},
	"00000048": {"hex": "00000048", "name": "ESME_RINVSRCTON", "description": "Invalid source address TON"},
	"00000049": {"hex": "00000049", "name": "ESME_RINVSRCNPI", "description": "Invalid source address NPI"},
	"00000050": {"hex": "00000050", "name": "ESME_RINVDSTTON", "description": "Invalid destination address TON"},
	"00000051": {"hex": "00000051", "name": "ESME_RINVDSTNPI", "description": "Invalid destination address NPI"},
	"00000053": {"hex": "00000053", "name": "ESME_RINVSYSTYP", "description": "Invalid system_type field"},
	"00000054": {"hex": "00000054", "name": "ESME_RINVREPFLAG", "description": "Invalid replace_if_present flag"},
	"00000055": {"hex": "00000055", "name": "ESME_RINVNUMMSGS", "description": "Invalid number of messages"},
	"00000058": {"hex": "00000058", "name": "ESME_RTHROTTLED",
		"description": "Throttling error (ESME has exceeded allowed message limits)"},
	"00000061": {"hex": "00000061", "name": "ESME_RINVSCHED", "description": "Invalid scheduled delivery time"},
	"00000062": {"hex": "00000062", "name": "ESME_RINVEXPIRY",
		"description": "Invalid message validity period (expiry time)"},
	"00000063": {"hex": "00000063", "name": "ESME_RINVDFTMSGID",
		"description": "Predefined message invalid or not found"},
	"00000064": {"hex": "00000064", "name": "ESME_RX_T_APPN", "description": "ESME Receiver Temporary App Error Code"},
	"00000065": {"hex": "00000065", "name": "ESME_RX_P_APPN", "description": "ESME Receiver Permanent App Error Code"},
	"00000066": {"hex": "00000066", "name": "ESME_RX_R_APPN", "description": "ESME Receiver Reject Message Error Code"},
	"00000067": {"hex": "00000067", "name": "ESME_RQUERYFAIL", "description": "query_sm request failed"},
	"000000c0": {"hex": "000000c0", "name": "ESME_RINVOPTPARSTREAM",
		"description": "Error in the optional part of the PDU Body"},
	"000000c1": {"hex": "000000c1", "name": "ESME_ROPTPARNOTALLWD", "description": "Optional paramenter not allowed"},
	"000000c2": {"hex": "000000c2", "name": "ESME_RINVPARLEN", "description": "Invalid parameter length"},
	"000000c3": {"hex": "000000c3", "name": "ESME_RMISSINGOPTPARAM",
		"description": "Expected optional parameter missing"},
	"000000c4": {"hex": "000000c4", "name": "ESME_RINVOPTPARAMVAL", "description": "Invalid optional parameter value"},
	"000000fe": {"hex": "000000fe", "name": "ESME_RDELIVERYFAILURE",
		"description": "Delivery Failure (used for data_sm_resp)"},
	"000000ff": {"hex": "000000ff", "name": "ESME_RUNKNOWNERR", "description": "Unknown error"},
	"0000041a": {"hex": "0000041a", "name": "AIRWIDE_BARRED_DEST",
		"description": "Subscriber not in LDAP"},
}

var mandatory_parameter_lists = map[string][]map[string]interface{}{
	"bind_transmitter": { // SMPP v3.4, section 4.1.1, table 4-1, page 46
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
		{"name": "password", "min": 1, "max": 9, "var": true, "type": "string", "map": nil},
		{"name": "system_type", "min": 1, "max": 13, "var": true, "type": "string", "map": nil},
		{"name": "interface_version", "min": 1, "max": 1, "var": false, "type": "hex", "map": nil},
		{"name": "addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "address_range", "min": 1, "max": 41, "var": true, "type": "string", "map": nil},
	},
	"bind_transmitter_resp": { // SMPP v3.4, section 4.1.2, table 4-2, page 47
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
	},
	"bind_receiver": { // SMPP v3.4, section 4.1.3, table 4-3, page 48
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
		{"name": "password", "min": 1, "max": 9, "var": true, "type": "string", "map": nil},
		{"name": "system_type", "min": 1, "max": 13, "var": true, "type": "string", "map": nil},
		{"name": "interface_version", "min": 1, "max": 1, "var": false, "type": "hex", "map": nil},
		{"name": "addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "address_range", "min": 1, "max": 41, "var": true, "type": "string", "map": nil},
	},
	"bind_receiver_resp": { // SMPP v3.4, section 4.1.4, table 4-4, page 50
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
	},
	"bind_transceiver": { // SMPP v3.4, section 4.1.5, table 4-5, page 51
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
		{"name": "password", "min": 1, "max": 9, "var": true, "type": "string", "map": nil},
		{"name": "system_type", "min": 1, "max": 13, "var": true, "type": "string", "map": nil},
		{"name": "interface_version", "min": 1, "max": 1, "var": false, "type": "hex", "map": nil},
		{"name": "addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "address_range", "min": 1, "max": 41, "var": true, "type": "string", "map": nil},
	},
	"bind_transceiver_resp": { // SMPP v3.4, section 4.1.6, table 4-6, page 52
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
	},
	"outbind": { // SMPP v3.4, section 4.1.7.1, page 54
		{"name": "system_id", "min": 1, "max": 16, "var": true, "type": "string", "map": nil},
		{"name": "password", "min": 1, "max": 9, "var": true, "type": "string", "map": nil},
	},
	"unbind": { // SMPP v3.4, section 4.2.1, table 4-7, page 56
	},
	"unbind_resp": { // SMPP v3.4, section 4.2.2, table 4-8, page 56
	},
	"generic_nack": { // SMPP v3.4, section 4.3.1, table 4-9, page 57
	},
	"submit_sm": { // SMPP v3.4, section 4.4.1, table 4-10, page 59-61
		{"name": "service_type", "min": 1, "max": 6, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "dest_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "dest_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "destination_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "esm_class", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "protocol_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "priority_flag", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "schedule_delivery_time", "min": 1, "max": 17, "var": false, "type": "string", "map": nil},
		{"name": "validity_period", "min": 1, "max": 17, "var": false, "type": "string", "map": nil},
		{"name": "registered_delivery", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "replace_if_present_flag", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "data_coding", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_default_msg_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_length", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "short_message", "min": 0, "max": 254, "var": "sm_length", "type": "xstring", "map": nil},
	},
	"submit_sm_resp": { // SMPP v3.4, section 4.4.2, table 4-11, page 67
		{"name": "message_id", "min": 0, "max": 65, "var": true, "type": "string", "map": nil},
	},
	"submit_multi": { // SMPP v3.4, section 4.5.1, table 4-12, page 69-71
		{"name": "service_type", "min": 1, "max": 6, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "number_of_dests", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "dest_address", "min": 0, "max": 0, "var": "number_of_dests", "type": "dest_address",
			"map": nil},
		{"name": "esm_class", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "protocol_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "priority_flag", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "schedule_delivery_time", "min": 1, "max": 17, "var": false, "type": "string",
			"map": nil},
		{"name": "validity_period", "min": 1, "max": 17, "var": false, "type": "string", "map": nil},
		{"name": "registered_delivery", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": nil},
		{"name": "replace_if_present_flag", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": nil},
		{"name": "data_coding", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_default_msg_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_length", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "short_message", "min": 0, "max": 254, "var": "sm_length", "type": "xstring",
			"map": nil},
	},
	"dest_address": { // SMPP v3.4, section 4.5.1.1, table 4-13, page 75
		{"name": "dest_flag", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		// "sme_dest_address" or "distribution_list" goes here
	},
	"sme_dest_address": { // SMPP v3.4, section 4.5.1.1, table 4-14, page 75
		{"name": "dest_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "dest_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "destination_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
	},
	"distribution_list": { // SMPP v3.4, section 4.5.1.2, table 4-15, page 75
		{"name": "dl_name", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
	},
	"submit_multi_resp": { // SMPP v3.4, section 4.5.2, table 4-16, page 76
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "no_unsuccess", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "unsuccess_sme", "min": 0, "max": 0, "var": "no_unsuccess",
			"type": "unsuccess_sme", "map": nil},
	},
	"unsuccess_sme": { // SMPP v3.4, section 4.5.2.1, table 4-17, page 77
		{"name": "dest_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "dest_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "destination_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "error_status_code", "min": 4, "max": 4, "var": false, "type": "integer", "map": nil},
	},
	"deliver_sm": { // SMPP v3.4, section 4.6.1, table 4-18, page 79-81
		{"name": "service_type", "min": 1, "max": 6, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "dest_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "dest_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "destination_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "esm_class", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "protocol_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "priority_flag", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "schedule_delivery_time", "min": 1, "max": 1, "var": false, "type": "string",
			"map": nil},
		{"name": "validity_period", "min": 1, "max": 1, "var": false, "type": "string", "map": nil},
		{"name": "registered_delivery", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "replace_if_present_flag", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": nil},
		{"name": "data_coding", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_default_msg_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_length", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "short_message", "min": 0, "max": 254, "var": "sm_length", "type": "xstring", "map": nil},
	},
	"deliver_sm_resp": { // SMPP v3.4, section 4.6.2, table 4-19, page 85
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
	},
	"data_sm": { // SMPP v3.4, section 4.7.1, table 4-20, page 87-88
		{"name": "service_type", "min": 1, "max": 6, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "dest_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "dest_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "destination_addr", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "esm_class", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "registered_delivery", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "data_coding", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
	},
	"data_sm_resp": { // SMPP v3.4, section 4.7.2, table 4-21, page 93
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
	},
	"query_sm": { // SMPP v3.4, section 4.8.1, table 4-22, page 95
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
	},
	"query_sm_resp": { // SMPP v3.4, section 4.7.2, table 4-21, page 93
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "final_date", "min": 1, "max": 17, "var": false, "type": "string", "map": nil},
		{"name": "message_state", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "error_code", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
	},
	"cancel_sm": { // SMPP v3.4, section 4.9.1, table 4-24, page 98-99
		{"name": "service_type", "min": 1, "max": 6, "var": true, "type": "string", "map": nil},
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "dest_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_ton"},
		{"name": "dest_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer", "map": "addr_npi"},
		{"name": "destination_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
	},
	"cancel_sm_resp": { // SMPP v3.4, section 4.9.2, table 4-25, page 100
	},
	"replace_sm": { // SMPP v3.4, section 4.10.1, table 4-26, page 102-103
		{"name": "message_id", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 21, "var": true, "type": "string", "map": nil},
		{"name": "schedule_delivery_time", "min": 1, "max": 17, "var": false, "type": "string",
			"map": nil},
		{"name": "validity_period", "min": 1, "max": 17, "var": false, "type": "string", "map": nil},
		{"name": "registered_delivery", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "replace_if_present_flag", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": nil},
		{"name": "data_coding", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_default_msg_id", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "sm_length", "min": 1, "max": 1, "var": false, "type": "integer", "map": nil},
		{"name": "short_message", "min": 0, "max": 254, "var": "sm_length", "type": "xstring", "map": nil},
	},
	"replace_sm_resp": { // SMPP v3.4, section 4.10.2, table 4-27, page 104
	},
	"enquire_link": { // SMPP v3.4, section 4.11.1, table 4-28, page 106
	},
	"enquire_link_resp": { // SMPP v3.4, section 4.11.2, table 4-29, page 106
	},
	"alert_notification": { // SMPP v3.4, section 4.12.1, table 4-30, page 108
		{"name": "source_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "source_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "source_addr", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
		{"name": "esme_addr_ton", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_ton"},
		{"name": "esme_addr_npi", "min": 1, "max": 1, "var": false, "type": "integer",
			"map": "addr_npi"},
		{"name": "esme_addr", "min": 1, "max": 65, "var": true, "type": "string", "map": nil},
	},
}
